services:
  sentinel-dashboard:
    image: jalena/sentinel-dashboard:latest
    container_name: sentinel-dashboard
    restart: always
    environment:
      SERVER_PORT: 8858
      AUTH_USERNAME: sentinel
      AUTH_PASSWORD: 123456
    ports:
      - "8858:8858"
    
